# Copyright 2022 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
skipsdist=True
skip_missing_interpreters = True
envlist = lint, unit, scenario, static-charm, static-lib

[vars]
src_path = {toxinidir}/src/
tst_path = {toxinidir}/tests/
lib_path = {toxinidir}/lib/charms/tempo_coordinator_k8s
all_path = {[vars]src_path} {[vars]tst_path} {[vars]lib_path}
uv_flags = --frozen --isolated

[testenv]
allowlist_externals = uv
basepython = python3
setenv =
  PYTHONPATH = {toxinidir}:{toxinidir}/lib:{[vars]src_path}
  PYTHONBREAKPOINT=ipdb.set_trace
  PY_COLORS=1
passenv =
  PYTHONPATH
  CI
  # for faster local itest iterations: pack once, pass the packed charm to pytest with this envvar
  WORKER_CHARM_PATH
  # CI v1 will set this
  CHARM_PATH

[testenv:lock]
description = Update uv.lock with the latest deps
commands =
  uv lock --upgrade --no-cache --project {toxinidir}

[testenv:fmt]
description = "Format the code"
commands =
    uv run {[vars]uv_flags} --all-extras ruff check --fix-only {[vars]all_path}
    uv run {[vars]uv_flags} --all-extras ruff format {[vars]all_path}

[testenv:lint]
description = Lint the code
allowlist_externals =
  {[testenv]allowlist_externals}
  /usr/bin/env
commands =
    uv run {[vars]uv_flags} --all-extras ruff check {[vars]all_path}
    uv run {[vars]uv_flags} --all-extras pyright {[vars]src_path} {[vars]lib_path}
    /usr/bin/env sh -c 'for m in $(git diff main --name-only {[vars]lib_path} | sed -E 's@^coordinator/@@g'); do if git ls-tree -r HEAD --name-only | grep -q "^$m$"; then  if ! git diff main $m | grep -q "+LIBPATCH\|+LIBAPI"; then echo "You forgot to bump the version on $m!"; exit 1; fi; fi; done'

[testenv:unit]
description = Run unit tests
commands =
    uv run {[vars]uv_flags} --all-extras pytest {[vars]tst_path}interface {posargs}
    uv run {[vars]uv_flags} --all-extras coverage run --source={[vars]src_path} -m pytest \
        {[vars]tst_path}unit {[vars]tst_path}unit {posargs}
    uv run {[vars]uv_flags} --all-extras coverage report

[testenv:integration]
description = Run integration tests
setenv =
  PYTHONPATH = {env:PYTHONPATH:+:${env:PYTHONPATH}}:{toxinidir}/..:{toxinidir}/src:{toxinidir}/lib
commands =
    uv run {[vars]uv_flags} --all-extras pytest -vv --exitfirst {toxinidir}/../tests/integration {posargs}

[testenv:static]
description = Static code checking
allowlist_externals =
  {[testenv]allowlist_externals}
  /usr/bin/env
commands =
    uv run {[vars]uv_flags} --all-extras pyright {[vars]src_path} {[vars]lib_path}
    /usr/bin/env sh -c 'for m in $(git diff main --name-only {[vars]lib_path} | sed -E 's@^coordinator/@@g'); do if git ls-tree -r HEAD --name-only | grep -q "^$m$"; then  if ! git diff main $m | grep -q "+LIBPATCH\|+LIBAPI"; then echo "You forgot to bump the version on $m!"; exit 1; fi; fi; done'
